apiVersion: v1
kind: Pod
metadata:
    labels:
        podname: testpod
spec:
    containers:
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command:
      - cat
      tty: true
#    - name: kaniko
#      image: gcr.io/kaniko-project/executor:debug
#      imagePullPolicy: Always
#      command:
#      - /busybox/cat
#      tty: true
#      volumeMounts:
#       - name: kaniko-secret
#         mountPath: /secret
#      env:
#        - name: GOOGLE_APPLICATION_CREDENTIALS
#          value: /secret/kaniko-secret.json
#    volumes:
#        - name: kaniko-secret
#          secret:
#            secretName: kaniko-secret
    serviceAccount: jenkins
